### ISSUE TITLE
user search always shows blank

### ISSUE THREAD

**Issue by catnotadog** [fa0311/vrchat_mobile_client#89]
### OS

android 12

### Device name

Samsung galaxy s20 fe 5g

### Country of origin of connection

Canada

### Where you downloaded the app

Google Play Store

### Have you reinstalled it ?

Yes

### Bug description

User search always returns empty

### Steps to reproduce

1. search for user

### Relevant error message output

```shell
"without"
```

**Comment by fa0311** [comment]
This Issues seems to occur when there are less than 50 search results.

**Comment by fa0311** [comment]
Released
